### ISSUE TITLE
Raspbian Pi BOINC 7.6.33 [error] No signing key from account manager

### ISSUE THREAD

**Issue by brierjon** [davidpanderson/science_united#11]
Running Raspbian Pi Stretch with latest patches the current packaged BOINC manager for the OS is version 7.6.33.

Attaching to the account manager "Science United" results in the "successful attachment" step of the attach to account manager process, but attachment is not a success. 

The logs show the following steps:

- Fetching configuration file from https://scienceunited....
- Contacting account manager at https://scienceunited....
- Account manager contact succeeded
- [error] No signing key from account manager

No other info is displayed in the Event log after the error.

The result is no attachment succeeds and viewing the Tools menu the selection does not change and still displays "Add project.... , Use account manager..., etc)" Where it usually would show the attached account manager.

Is this a science united issue or due to the outdated client available to Raspbian PI?

**Comment by davidpanderson** [comment]
Science United won't work with BOINC clients earlier than 7.10.
7.12 is recommended.

**Comment by brierjon** [comment]
That is what I suspected and missed that note to BOINC in the documentation since I was connecting directly from the client.
