### ISSUE TITLE
Unable to attach account manager to clients

### ISSUE THREAD

**Issue by TameTheGame** [davidpanderson/science_united#15]
I'm receiving the error "AM reply parse error" when attempting to attach the account manager to the client. I'm using Ubuntu Server 18.04.2 LTS and boinc-client version 7.14.2.

When attempting to attach my Windows 10 machine using the BOINC Manager, it states that the connection was successful even though the account manager does not actually attach and no work is downloaded. 

Strangely, both machines appear on the "Your computers" page of Science United, with the "Last contact" field showing the time since I last attempted to connect the account manager. In the machine details though, the "Number of times client has contacted server" field stands at "0."

**Comment by davidpanderson** [comment]
Thanks for the report.  I fixed both problems.
