### ISSUE TITLE
"Science united status" emails don't honor settings

### ISSUE THREAD

**Issue by hmijail** [davidpanderson/science_united#17]
I am getting "Science United status" emails daily, even though I configured my emails settings for them to be sent monthly.

This was initially reported at https://scienceunited.org/forum_thread.php?id=75#192 . I was told to maybe try here.

Possibly related: conversely, I never got a notification for the responses in the forum.

**Comment by davidpanderson** [comment]
The status email problem should be fixed now.

"Notification" emails (friend requests, posts to subscribed threads, PMs) are working
as far as I can tell.
If not please point me to an example.

**Comment by hmijail** [comment]
Didn't receive any new mail, does seem to be fixed. Closing.
