### ISSUE TITLE
Home page error

### ISSUE THREAD

**Issue by TameTheGame** [davidpanderson/science_united#19]
The following error is displayed on the home page after logging in, underneath "Welcome, (username)" and above "Recent contribution."

`Notice: Use of undefined constant CURRENT_CLIENT_VERSION - assumed 'CURRENT_CLIENT_VERSION' in /mydisks/a/users/boincadm/science_united/su_user.inc on line 73 Notice: Use of undefined constant CURRENT_CLIENT_VERSION - assumed 'CURRENT_CLIENT_VERSION' in /mydisks/a/users/boincadm/science_united/su_user.inc on line 73`

**Comment by davidpanderson** [comment]
Oops!  Fixed - thanks.
