### ISSUE TITLE
BOINC@TACC shows error message

### ISSUE THREAD

**Issue by jakobjakobson13** [davidpanderson/science_united#35]
When the boinc connects to BOINC@TACC (`https://boinc.tacc.utexas.edu`) the following error gets reported: `BOINC@TACC | This project is using an old URL. When convenient, remove the project, then add http://boinc.tacc.utexas.edu/` .

PS: I reported the bug also at the boinc issue tracker ([https://github.com/BOINC/boinc/issues/3850](https://github.com/BOINC/boinc/issues/3850)) and was referred to this bug tracker.

**Comment by davidpanderson** [comment]
The URL of that project is http://.
Science United now uses this URL, so this error should go away soon.

**Comment by jakobjakobson13** [comment]
Thanks.
