### ISSUE TITLE
Failed to update account manager

### ISSUE THREAD

**Issue by KwisatzJim** [davidpanderson/science_united#37]
On my Windows PC it hasn't been able to connect to the account manager for 3 days.  
When I manually tell it to sync with Science United it gives error "Failed to update account manager"
It's running Windows 10 Pro 21H1.
I've verified the Windows Firewall is set to allow BOINC traffic

My 3 linux boxes are syncing fine.

**Comment by KwisatzJim** [comment]
event log says: 
Project communication failed: attempting access to reference site
Internet access OK - project servers may be temporarily down

**Comment by davidpanderson** [comment]
There's a workaround:
https://boinc.berkeley.edu/forum_thread.php?id=14422

We'll fix the problem permanently soon.

**Comment by KwisatzJim** [comment]
worked perfectly, thank you so much!
