### ISSUE TITLE
forum moderation

### ISSUE THREAD

**Issue by wigiglenekit** [davidpanderson/science_united#40]
I noticed a spam attack on the science united forum
how long has this been going on?
In theory, we can write a script that on the backend every time a new message will send it to the common chat room of moderators, for example, telegram
this way we can promptly ban all this
I couldn't find the "forum" part of su in source code, so i cant check my idea locally first, so i'm writing it here

**Comment by davidpanderson** [comment]
Thanks for pointing this out.
I delete the spammer accounts and posts.
Hopefully this is a one-time thing;
if it persists we can think about a solution.
