### ISSUE TITLE
cannot use custom settings for home, school, and work 

### ISSUE THREAD

**Issue by ellipinsky** [davidpanderson/science_united#42]
Under Settings / Computing / customize, it is possible to configure separate computing preferences for home, school, and work.  However, it appears there is no way in the site to associate these preferences with computers.

Is the home/school/work feature supposed to work in SU?  I am comparing with a similar feature in Einstein@Home.

**Comment by davidpanderson** [comment]
Thanks for pointing this out; I'll fix it.
Fixed in 7c2f75a
