### ISSUE TITLE
Enhancement: Leaderboards?

### ISSUE THREAD

**Issue by JEMcats** [davidpanderson/science_united#45]
Can we have a computing leaderboard showing CPU and GPU time that you enroll in to compare who has done the most work, just a fun element to Science United?

**Comment by davidpanderson** [comment]
So far I've avoided leaderboard-type features in SU,
but maybe it's time to add them.
I'll look into this.

**Comment by JEMcats** [comment]
Sounds good no rush what so ever, thank you!

**Comment by davidpanderson** [comment]
Prototype leaderboards:
https://scienceunited.org/su_lb_intro.php
It's opt-in; you and I are opted in.

Please review/explore.
Currently it shows info about the computers of opted-in user;
I think this is important, but are we showing too much info?
(it's the same as what's shown on all BOINC projects).

**Comment by JEMcats** [comment]
That's super cool, you did a good job.

**Comment by davidpanderson** [comment]
Thanks for suggesting it.  I'll make it public.

**Comment by JEMcats** [comment]
Sounds good, thank you!

**Comment by JEMcats** [comment]
You should put leaderboards in the community section on su_home.php.

**Comment by davidpanderson** [comment]
Good idea.  I did that, and also added it on the menu bar (under Community)
and also posted a news item, which will also appear as a Notice in the Manager.

**Comment by JEMcats** [comment]
Thank you, @davidpanderson.
