### ISSUE TITLE
Shall we do review with policies like public, private fcs options

### ISSUE THREAD

**Issue by Arentaz** [davidpanderson/science_united#46]
https://github.com/davidpanderson/science_united/blob/b7e4bfb1a75cec7c4bccc1022fe1c18fff6da158/make_accounts.php#L42

**Comment by davidpanderson** [comment]
Please clarify

**Comment by Arentaz** [comment]
We should (in this case), but thats my opinion. 
- In that script we refer into deep Classes(absence constructor) without parameters. Not sure, but propably unset (visibility of input parameter) parameter. Other side is unused instance of SUAccount. 
- var user in this example is prefered call only new Class (instance with parsed input from whatever). 
And big Unknown is Time(); - for new user is important realtime not localsystem. 
Thats couple thoughts. At all any code isnt bad or wrong. But effectively work in team is hardest part. :)
