### ISSUE TITLE
Am no longer able to customize my Science United computing preferences

### ISSUE THREAD

**Issue by rollynoel** [davidpanderson/science_united#47]
Tried with different browsers. Only able to select one of the Low power/Standard/Maximum computing radio buttons

**Comment by davidpanderson** [comment]
I can't reproduce this.  When you go to the computing preferences page
(https://scienceunited.org/su_compute_prefs.php)
there should be a link "Customize your preferences"
(or if you're already using custom prefs, "Show").
This takes you to a form for specifying prefs.

Are you not seeing these links?

**Comment by rollynoel** [comment]
Thanks for your response. I see I have to scroll down (it was off screen on my monitor) to click on Edit preferences
