### ISSUE TITLE
Low power set 100% cpus.

### ISSUE THREAD

**Issue by sebastianmbobrecki** [davidpanderson/science_united#7]
In computing settings selecting "Low power" set usage of 100% of processors, when it should 25%.
`Use 25% of processors, and stop computing when computer is idle`

**Comment by sebastianmbobrecki** [comment]
I see that in su_compute_prefs.php it is named "low_power" but in su_compute_prefs.inc it is named "green",

**Comment by davidpanderson** [comment]
Oops!  Thanks, fixed
