### ISSUE TITLE
There's msgid to msgstr mismatch between index.php and en.po.

### ISSUE THREAD

**Issue by sebastianmbobrecki** [davidpanderson/science_united#8]
There's msgid to msgstr mismatch between index.php and en.po.

en.po:
`#: index.php:170
msgid ""
"Science United is funded by the %1National Science Foundation%2, award "
"#1664190, and is based at the %3University of California, Berkeley%4."
msgstr ""`

index.php:
`echo tra("Science United is funded by the %1National Science Foundation%2, award #1664190, and is based at the %3University of California, Berkeley%4.
        Image credits: CERN and NIAID.",
        "<a href=https://nsf.gov>", "</a>",
        "<a href=https://berkeley.edu>", "</a>"
);`

**Comment by davidpanderson** [comment]
Fixed; thanks.
